### ISSUE TITLE
Take the analytics keys out of webpack.config.js

### ISSUE THREAD

**Issue by Callmenorm** [mikeyamadeo/react-workshop#1]
I don't think that the google analytics and errorception stuff should be in the webpack.config.js. But even if you want that in there, I think the ancestor cloud keys should be taken out. But if you're going to leave the other stuff in there then there needs to be some way for other people to put their own keys in.

**Comment by mikeyamadeo** [comment]
Great catch! Thank you! Please keep the issues coming as you find them.
